### ISSUE TITLE
appending screenshot of results of each commands line would great

### ISSUE THREAD

**Issue by ainilaha** [dgrtwo/tidy-text-mining#15]
appending screenshot of results of each commands line may very nice to some people do not want read word by word or people already finished the book and looking for something they forget. Because with the screenshots they don't need try it again.

**Comment by dgrtwo** [comment]
The output of the results do appear as text in the book output at tidytextmining.com- see [here](http://tidytextmining.com/dtm.html) for example:

![image](https://cloud.githubusercontent.com/assets/994718/20333565/6558715c-ab81-11e6-99a6-803ee567fdd6.png)

They don't appear in the Rmd files in this repository, but that's because they're not yet compiled.
