### ISSUE TITLE
Mining financial articles - Error in mutate_impl(.data, dots) : 1: failed to load HTTP resource

### ISSUE THREAD

**Issue by t1ber1us** [dgrtwo/tidy-text-mining#32]
Hi, 

I get the error above in section 5.3.1 when executing the code to download articles for technology stocks. I've both typed it in myself and copied and pasted the text from here with the same result. I'm guessing this is something in the wider set up of my pc or the world, but would be grateful for any thoughts you have on how I might fix it.

Thanks,

Ian

**Comment by juliasilge** [comment]
I believe this is an error from the XML package downloading the finance data; sounds like R is not successfully accessing that data. You might need to do some debugging around accessing the internet through R? Also perhaps try just doing a few of the companies; I have heard some people have trouble with all of those, especially Twitter and IBM.

If it makes you feel better, someone else also [got this error when trying to run the code from the book](http://juliasilge.com/blog/Tidy-Text-Mining/#comment-3270919474).

**Comment by rizwaan** [comment]
Looks like there is some sort of limitation on the corpus's dimension.
The code works if there are only 5 elements in the company vector. Couldnt investigate any further though.

**Comment by chankamiperera** [comment]
hi, 
when I try the code mention in topic modeling part. I got a error mention like this. 
Error in LDA(dtm, k, method = "Gibbs", control = list(nstart = nstart,  : 
  Each row of the input matrix needs to contain at least one non-zero entry
Please help me to fix it.
Thank you.

**Comment by juliasilge** [comment]
Hello @chankamiperera! I don't think you are using code from our book, because I don't believe we have any Gibbs method fitting at all. If you are running into an error that we might be able to help with, can you make a [small, reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) to show the error? You also might consider posting your problem on Stack Overflow, because the function `LDA()` is from the topicmodels package, not our tidytext package, so you might get faster help (or at least help from more people) there. I have SO questions tagged `tidytext` on a feed so I will always see them.
