### ISSUE TITLE
small typo, fixed in repo, but not in published web version

### ISSUE THREAD

**Issue by koalabearski** [dgrtwo/tidy-text-mining#42]
In section 2.2 the web page reads "this index (using integer division) counts up sections of 100 lines of text", but in the github repo this has already been corrected to "this index (using integer division) counts up sections of **80** lines of text.".  Might be a sign they are out of sync.

**Comment by juliasilge** [comment]
Yep, we're having some issues with deploying via GitHub pages right now and are in the process of switching over to Netlify. Just need some time to get it all done!

**Comment by juliasilge** [comment]
@dgrtwo I have some of the scaffolding done here to switch us over to Netlify instead of GitHub pages, based on what I've done with my blog and [how Hadley switched Advanced R over](https://github.com/rstudio/bookdown/issues/459#issuecomment-329376925). Here are some things I know you need to do (that I can't do, since it is all your accounts):

- Sign up for Netlify, connect it to this repo, etc.
- Figure out what the Netlify ID is for the site and put it in the [`.netlify` file](https://github.com/dgrtwo/tidy-text-mining/blob/master/.netlify)
- Save a PAT in your Travis config
- Push so that it will build :ok_hand:
- Eventually, set Netlify to forward to [tidytextmining.com](http://tidytextmining.com/), turn on https, etc. This is further down the road, once we have the site actually building.

There might still be other things that need fixing, but this is at least the starting place.

**Comment by dgrtwo** [comment]
OK, working on this now! Only question is what the variable name for the Netlify PAT should be in Travis; I can't find that in any of the guides.

**Comment by dgrtwo** [comment]
Never mind, found that in your new commit! Stand by.

**Comment by dgrtwo** [comment]
Hmm; it's published to Netlify [here](https://amazing-wright-6fba72.netlify.com), but it did so incorrectly. It didn't build then point to the _book subfolder, it just uploaded the content directly (e.g. try adding index.Rmd to the end and it downloads that file).

I don't have experience with Netlify so I'm not currently sure what to try next. I've added you as an administrator and I'll continue trying tomorrow!

**Comment by juliasilge** [comment]
We are now all published to Netlify, updating with pushes from GitHub, and have https turned on even! 🎉

**Comment by koalabearski** [comment]
Sweet!
